var actions = {"旋轉飛入": {"p": {"fade": "in", "rotate": 720},
	"a": "drain",
	"o": ["elems", "fade", "rotate", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "旋轉飛出": {"p": {"fade": "out", "rotate": -720},
	"a": "drain",
	"o": ["elems", "fade", "rotate", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "淡入": {"p": {"fade": "in"},
	"a": "fade",
	"o": ["elems", "fade", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "淡出": {"p": {"fade": "out"},
	"a": "fade",
	"o": ["elems", "fade", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "翻頁(向左)": {"p": {"flip": "left"},
	"a": "pageFlip",
	"o": ["elems", "flip", "turns", "overshoot", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "翻頁(向右)": {"p": {"flip": "right"},
	"a": "pageFlip",
	"o": ["elems", "flip", "turns", "overshoot", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "翻頁(向上)": {"p": {"flip": "up"},
	"a": "pageFlip",
	"o": ["elems", "flip", "turns", "overshoot", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "翻頁(向下)": {"p": {"flip": "down"},
	"a": "pageFlip",
	"o": ["elems", "flip", "turns", "overshoot", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "翻轉飛入": {"p": {"fade": "in", "rotate": 720, "flip": "right"},
	"a": "phantomZone",
	"o": ["elems", "fade", "rotate", "flip", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "翻轉飛出": {"p": {"fade": "out", "rotate": -720, "flip": "left"},
	"a": "phantomZone",
	"o": ["elems", "fade", "rotate", "flip", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "旗幟揮舞": {"p": {"rotate": -720, "perspectiveOrigin": "top"-"right"},
	"a": "raceFlag",
	"o": ["elems", "rotate", "perspectiveOrigin", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "向左滑入": {"p": {"move": "left"},
	"a": "slide",
	"o": ["elems", "move", "overshoot", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "向右滑入": {"p": {"move": "right"},
	"a": "slide",
	"o": ["elems", "move", "overshoot", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "向上滑入": {"p": {"move": "up"},
	"a": "slide",
	"o": ["elems", "move", "overshoot", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "向下滑入": {"p": {"move": "down"},
	"a": "slide",
	"o": ["elems", "move", "overshoot", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "向左旋轉": {"p": {"flip": "left"},
	"a": "spin",
	"o": ["elems", "flip", "turns", "overshoot", "duration", "timing", "delay", "iteration", "playstate"]},
 "向右旋轉": {"p": {"flip": "right"},
	"a": "spin",
	"o": ["elems", "flip", "turns", "overshoot", "duration", "timing", "delay", "iteration", "playstate"]},
 "向上旋轉": {"p": {"flip": "up"},
	"a": "spin",
	"o": ["elems", "flip", "turns", "overshoot", "duration", "timing", "delay", "iteration", "playstate"]},
 "向下旋轉": {"p": {"flip": "down"},
	"a": "spin",
	"o": ["elems", "flip", "turns", "overshoot", "duration", "timing", "delay", "iteration", "playstate"]},
 "向左滾動": {"p": {"move": "left"},
	"a": "toss",
	"o": ["elems", "move", "overshoot", "perspectiveOrigin", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "向右滾動": {"p": {"move": "right"},
	"a": "toss",
	"o": ["elems", "move", "overshoot", "perspectiveOrigin", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "向上滾動": {"p": {"move": "up"},
	"a": "toss",
	"o": ["elems", "move", "overshoot", "perspectiveOrigin", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "向下滾動": {"p": {"move": "down"},
	"a": "toss",
	"o": ["elems", "move", "overshoot", "perspectiveOrigin", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "對角翻轉向左": {"p": {"flip": "left"},
	"a": "twirl",
	"o": ["elems", "flip", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "對角翻轉向右": {"p": {"flip": "right"},
	"a": "twirl",
	"o": ["elems", "flip", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "放大(125%)": {"p": {"scale": {"from": "100%", "to": "125%"}, "shadow": "true", "move": "left"},
	"a": "zoom",
	"o": ["elems", "scale", "shadow", "move", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "縮小(75%)": {"p": {"scale": {"from": "100%", "to": "75%"}, "shadow": "false", "move": "left"},
	"a": "zoom",
	"o": ["elems", "scale", "shadow", "move", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "彈跳": {
	"p": {"scale": {"from": "100%", "to": "125%"}, 
		"shadow": "true", 
		"duration": "500ms", 
		"timing": "easeOutSine", 
		"iteration": "infinite", 
		"direction": "alternate"},
	"a": "bounce",
	"o": ["elems", "scale", "shadow", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "跳舞": {"p": {"duration": "500ms", "timing": "easeInOutBack", "iteration": "infinite", "direction": "alternate", "rotate": 45},
	"a": "dance",
	"o": ["elems", "rotate", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "懸掛搖擺": {"p": {"duration": "1000ms", "timing": "linear", "iteration": "infinite", "direction": "alternate", "rotate": 45, "overshoot": 0},
	"a": "hinge",
	"o": ["elems", "rotate", "overshoot", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "左右搖擺": {"p": {"duration": "1000ms", "timing": "ease"-"in"-"out", "iteration": "infinite", "direction": "alternate", "rotate": 45, "overshoot": 0},
	"a": "pendulum",
	"o": ["elems", "rotate", "overshoot", "duration", "timing", "delay", "iteration", "direction", "playstate"]},
 "搖晃": {"p": {"duration": "200ms", "timing": "linear", "iteration": "infinite", "direction": "alternate", "rotate": 5, "perspectiveOrigin": "center"},
	"a": "wobble",
	"o": ["elems", "rotate", "perspectiveOrigin", "duration", "timing", "delay", "iteration", "direction", "playstate"]}
}